theme: jekyll-theme-minimal

title: Team EBN
description: A group project lead by @morellam-dev, for Intro to Software Engineering at Kennesaw State University. 

logo: https://avatars1.githubusercontent.com/u/74070783?s=400&u=66e61e25df940fcf7785c8f9f9ac029da84bed74&v=4
